### PR TITLE
Use parser.Parse() instead of own parser

### PR DESCRIPTION
**Pull request by k1LoW**
ref: #112

### CODE REVIEW

**Comment by k1LoW** [comment]
I found that some cases were not considered, so I am committing them additionally

**Comment by k1LoW** [comment]
Fix cases of https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md#supported-literals

**Review by k2tzumi — APPROVED** [review]
Looks like additional testing is needed, but it looked good!

The extended syntax here can't be parsed by AST, can it?
https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md

**Comment by k1LoW** [comment]
> The extended syntax here can't be parsed by AST, can it?

It probably cannot be parsed. The current runn built-in function can be parsed as a function.

**Comment by k2tzumi** [comment]
> It probably cannot be parsed. The current runn built-in function can be parsed as a function.

As I thought.
Most of the syntax is supported, so it should not be a problem 👍

**Pull request merged**
