### PR TITLE
Use gopkg.in/yaml.v2 only for the first YAML parsing to keep the parsing stable

### PR DESCRIPTION
**Pull request by k1LoW**
Retry #147 #103 

Compatibility is ensured by a test that compares the output of `unmarshalAs*Steps()` and `unmarshalAs*Steps2()`.

### CODE REVIEW

**Review by k2tzumi — CHANGES_REQUESTED** [review]
Add gopkg.in/yaml.v2 to go.mod

I haven't followed the code yet, but I tried it and got the following error

`cannot find client: req`

**Comment by k1LoW** [comment]
> Add gopkg.in/yaml.v2 to go.mod

That seems to have already been added.

https://github.com/k1LoW/runn/blob/aa79afa91a2f8c1178da43da3d4245ee21ce7d37/go.mod#L38

> I haven't followed the code yet, but I tried it and got the following error

Is there any way to reproduce this?

**Comment by k2tzumi** [comment]
> That seems to have already been added.

I had missed it. 🙇 

> Is there any way to reproduce this?

I haven't written the test code, but I can reproduce it with openapi3 settings.

**Comment by k1LoW** [comment]
Thank you!!

**Comment by k1LoW** [comment]
Add your commit to this PR if you want.

**Comment by k2tzumi** [comment]
Another fix may have affected it.
https://github.com/k1LoW/runn/actions/runs/3123958948/jobs/5066943158#step:6:65

**Comment by k1LoW** [comment]
Fix https://github.com/k1LoW/runn/pull/159#issuecomment-1257296839 at #162

**Comment by k2tzumi** [comment]
> I haven't followed the code yet, but I tried it and got the following error

Error message has changed.

```
runner req error: open /path/to/api-docs.json: no such file or directory
```

I am specifying json by relative path, but maybe the behavior has changed.

**Comment by k2tzumi** [comment]
> I am specifying json by relative path, but maybe the behavior has changed.

Once I specified the full path, all scenarios were successful.

**Comment by k1LoW** [comment]
@k2tzumi Thank you for the error report!

Hopefully we can reproduce it well...

**Comment by k2tzumi** [comment]
I'll try to write a test case.

**Review by k2tzumi — APPROVED** [review]
There was another issue, but the PR itself here looks good

**Comment by k1LoW** [comment]
@k2tzumi Thank you!

**Pull request merged**
