### PR TITLE
More detailed error messages when retrieving columns

### PR DESCRIPTION
**Pull request by k2tzumi**
refs https://github.com/k1LoW/runn/issues/124

I could not reproduce the error in the test code using sqlite, so I would like to detail the error and check the contents.

### CODE REVIEW

**Comment by k2tzumi** [comment]
fm-

https://github.com/k1LoW/runn/runs/8103770196?check_suite_focus=true#step:7:55
```
--- FAIL: TestLoad (0.03s)
    operator_test.go:344: invalid desc: <nil>
{
  "a": {
    "bool": "[func]",
    "compare": "[func]",
    "filename": "include_a.yml",
    "int": "[func]",
    "steps": {
      "a": null,
      "e": {
        "exit_code": 0,
        "stderr": "",
        "stdout": "hello a\n"
      },
      "t": null
    },
    "string": "[func]",
    "upcase": "[func]",
    "urlencode": "[func]",
    "vars": {
      "filename": "include_a.yml"
    }
  },
  "b": {
    "bool": "[func]",
    "compare": "[func]",
    "int": "[func]",
    "steps": {
      "t": null,
      "t_func": null,
      "t_main": null
    },
    "string": "[func]",
    "upcase": "[func]",
    "urlencode": "[func]",
    "vars": {
      "filename": "include_a.yml",
      "filename_main": "include_main.yml"
    }
  }
}
{
  "filename": "include_main.yml"
}
FAIL
```

**Comment by k2tzumi** [comment]
https://github.com/k1LoW/runn/runs/8103860582?check_suite_focus=true#step:7:98

TestLoad and TestShard tests have a resource conflict-like appearance.

**Comment by k2tzumi** [comment]
# Execution Result

```
invalid column: evaluated created_at, but got DATETIME(2022-08-31 09:14:58): strconv.Atoi: parsing "2022-08-31 09:14:58": invalid syntax
```

`DATETIME` 

I guess we need to make it compatible with the date/time format.
A separate PR will be prepared.

**Review by k1LoW — APPROVED** [review]
Thank you!!

**Pull request merged**
